myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^(?P<course_no>\d+)/$', views.detail, name='detail'),
        #url(r'^base/$', views.base, name='base'),
        url(r'^topic_part1/$', views.topic_part1, name='topic_part1'),
        url(r'^topics/$', views.topics_view, name='topics'),
        url(r'^addtopic/$', views.addtopic, name='addtopic'),
        url(r'^topics/(?P<topic_id>\d+)/$', views.topicdetail, name='topicdetail'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.login, name='login'),
        url(r'^logout/$', views.logout, name='logout'),
        url(r'mycourses/',views.mycourses, name='mycourses')
        ]

mysiteS17zh/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls', namespace = 'myapp')),

]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Author(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    birthdate = models.DateField()
    # age = models.IntegerField()
    city = models.CharField(max_length=100, null=True,blank=True)

    def __str__(self):
        return self.firstname+' '+self.lastname

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    in_stock = models.BooleanField(default=True)
    numpages = models.IntegerField(null=True)

    def __str__(self):
        return self.title

class Student(User):
    PROVINCE_CHOICES = (
        ('AB','Alberta'), # First value is stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    age = models.IntegerField()
    class Meta:
        verbose_name="Student"
        verbose_name_plural="Students"

    def __str__(self):
        return self.first_name+' '+self.last_name

class Course(models.Model):
    course_no = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    textbook = models.ForeignKey(Book)
    students = models.ManyToManyField(Student,null=True, blank=True)

    def __str__(self):
        return self.title


class Topic(models.Model):
    subject = models.CharField(max_length=100, unique=True)
    intro_course = models.BooleanField(default=True)
    NO_PREFERENCE = 0
    MORNING = 1
    AFTERNOON = 2
    EVENING = 3
    TIME_CHOICES = (
        (0, 'No preference'),
        (1, 'Morning'),
        (2, 'Afternoon'),
        (3, 'Evening')
    )
    time = models.IntegerField(default=0, choices=TIME_CHOICES)
    num_responses = models.IntegerField(default=0)
    avg_age = models.IntegerField(default=20)

    def __str__(self):
        return str(self.id)+ ' '+ self.subject

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from myapp.models import Topic, Student

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['subject', 'intro_course', 'time', 'avg_age',]
        widgets = {'time': forms.RadioSelect(),}
        labels = {'avg_age': u'What is your age?', 'intro_course': u'This should be an introductory level course',
               'time': u'Preferred Time',}

class InterestForm(forms.Form):
    interest = forms.TypedChoiceField(widget=forms.RadioSelect, coerce=int, choices=((1, 'Yes'),(0, 'No')))
    age = forms.IntegerField(initial=20)
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments')

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Student
        fields = ['username', 'first_name', 'last_name', 'email', 'address', 'city', 'province', 'age']

myapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from myapp.models import Author, Book, Course, Topic
from myapp.forms import TopicForm, InterestForm,RegisterForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from datetime import datetime


# Create your views here.

# def index(request):
#     # courselist = Course.objects.all() [:10]
#     Authorlist = Author.objects.all().order_by('-birthdate')[:5]
#     response = HttpResponse()
#     heading1 = '<p>' + 'List of Author: ' + '</p>'
#     response.write(heading1)
#     for author in Authorlist:
#         para = '<p>' + str(author) + str(author.birthdate) + '</p>'
#         response.write(para)
#     return response

def index(request):
    courselist = Course.objects.all().order_by('title')[:10]
    return render(request, 'myapp/index.html', {'courselist': courselist})

# use class_based view
class IndexView(View):
    def get(self, request):
        course_list = Course.objects.all()[:10]

        # Deal with cookies
        if request.session.get('last_visit'):
            last_visit_time = request.session.get('last_visit')
            visits = request.session.get('visits', 0)

            # Use seconds instead of days for testing
            if (datetime.now() - datetime.strptime(last_visit_time[:-7], "%Y-%m-%d %H:%M:%S")).seconds > 0:
                request.session['visits'] = visits + 1
                request.session['last_visit'] = str(datetime.now())
        else:
            # this code was never reached, so the session was not being set
            request.session['last_visit'] = str(datetime.now())
            request.session['visits'] = 1
        if request.session.get('visits'):
            count = request.session.get('visits')
        else:
            count = 0
        context = {
                'course_list':course_list,
                'count': count
            }
        return render(request,'myapp/index.html',context)


# def about(request):
#     response = HttpResponse()
#     heading2 = '<p>' + 'This is a Course Listing APP.' + '<p>'
#     response.write(heading2)
#     return response

def about(request):
    return render(request, 'myapp/about.html')


# def detail(request, course_no):
#     titlelist = Course.objects.get(course_no=course_no)
#     response = HttpResponse()
#     heading1 = '<p>' + 'Details' + '<p>'
#     response.write(heading1)
#     response.write(titlelist.course_no)
#     response.write(titlelist.title)
#     response.write(titlelist.textbook)
#     return response

# def detail(request, course_no):
#     titlelist = Course.objects.get(course_no=course_no)
#     return render(request, 'myapp/detail.html', {'title': titlelist})

def detail(request, course_no):
    # course_title = Course.objects.get(course_no = course_no)
    course_title = get_object_or_404(Course, course_no=course_no)
    course_number = course_title.course_no
    textbook = course_title.textbook
    return render(request, 'myapp/detail0.html', {'coursetitle':course_title})
    # return render(request, 'myapp/detail.html', {'coursetitle': course_title})


# use class_based view
class CourseDetailView(View):
    def get(self,request,course_no):
        course = get_object_or_404(Course, course_no=course_no)
        return render(request, 'myapp/detail.html', {'course':course})


def topics(request):
    topiclist = Topic.objects.all()[:10]
    return render(request, 'myapp/topic.html', {'topiclist': topiclist})

def topic_part1(request):
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            return render()
    else:
        form = TopicForm()
        return render(request, 'myapp/topic_part1.html', {'form':form})

# def topic1_part1(request):#test
#     form = InterestForm()
#     return  render(request, 'myapp/topic_part1.html', {'form':form})

def topics_view(request):
    topiclist = Topic.objects.all().order_by("-num_responses")[:10]
    return render(request,'myapp/topic.html', {'topiclist':topiclist})


def addtopic(request):
    topiclist = Topic.objects.all().order_by("-num_responses")
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.num_responses = 1
            topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form = TopicForm()
    return render(request, 'myapp/addtopic.html', {'form':form, 'topiclist':topiclist} )

def topicdetail(request, topic_id):
    topic = get_object_or_404(Topic,pk=topic_id)
    if request.method=='POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            # the cleaned_data attribute only creates after validated
            if form.cleaned_data['interested'] == 1:
                #topic = form.save(commit=False)
                num = topic.num_responses
                topic.num_responses += 1
                topic.avg_age = int((form.cleaned_data['age'] + topic.avg_age *num)/(num+1))
                topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form = InterestForm()
    return render(request,'myapp/topicdetail.html',{'form':form,'topic':topic})

def register(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            # save form content to database if it is validated
            # stu= Student.objects.create_user(register_form.cleaned_data['username'])
            # stu.set_password(register_form.cleaned_data['password1'])
            register_form.save()
            return HttpResponseRedirect(reverse('myapp:login'))
    else:
        register_form = RegisterForm()
        return render(request,'myapp/register.html',{'register_form':register_form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                #print(request.user.first_name)
                return HttpResponseRedirect(reverse('myapp:index')) #
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))


def mycourses(request):
    course_list = Course.objects.filter(students__username=request.user)
    return render(request,'myapp/mycourses.html',{'course_list': course_list})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <p> This is a Course Listing APP. </p>
    <p><a href="/myapp">Index page</a> url namespacing </p>
{% endblock %}

myapp/templates/myapp/addtopic.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if topiclist %}
        <h2>Topic List:</h2>
        <ol>
            {% for topic in topiclist %}
                <li><a href="{% url 'myapp:topicdetail' topic.pk %}">{{ topic.subject }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
    <br><br><br>

    <p>You can add a new topic here.</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
        <input type="reset" value="Reset">
    </form>

{% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
        <title>Course Listing APP - {% block title %}Welcome!{% endblock %}</title>
    </head>

    <body>
        <div>
                {% if  request.user.is_authenticated %}
                    <h1>Hello {{ request.user.first_name }}</h1>
                    <div><a href="{% url 'myapp:logout' %}">Log out</a></div>
                    <div><a href="{% url 'myapp:mycourses' %}"> Courses I am registered in</a></div>
                {% else %}
                    <h1>Hello User</h1>
                    <div><a href="{% url 'myapp:register' %}"> Register</a></div>
                    <div><a href="{% url 'myapp:login' %}">Log in</a></div>
                {% endif %}
            {% block myhdg %}
            {% endblock %}
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                <li class="hbar1"><a href="{% url 'myapp:about' %}">Find out about this site</a></li>
                <li class="hbar1"><a href="{% url 'myapp:topics' %}">Find out the topic here</a></li>
                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
            </ul>
        </div>
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    {% if  request.user.is_authenticated %}
        Hello {{ request.user }}
    {% else %}
        Hello User
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if title %}
        <p>This is the detail of course: </p>
        <ol>
            <p>Course number: {{ title.course_no}}</p>
            <p>Course title: {{ title.title}} </p>
            <p>Course textbook: {{ title.textbook}} </p>
        </ol>
    {% else %}
        <strong>This courses does not exist!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
    {% if titlelist %}
        <p>This is the detail of course: </p>
        <ol>
            <p>Course number: </p>
            <li> {{ titlelist.course_no}} </li>
            <p>Course title: </p>
            <li> {{ titlelist.title}} </li>
            <p>Course textbook: </p>
            <li> {{ titlelist.textbook}} </li>
        </ol>
    {% else %}
        <strong>This courses does not exist!</strong>
    {% endif %}
    <p><a href="/myapp">Back</a> hardcoded url </p>
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if courselist %}
        <h2>List of Courses</h2>
        <ol>
            {% for course  in courselist %}
                <li> <a href={%url 'myapp:detail' course.course_no %}>{{ course.title}} </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="" method="post">
        {% csrf_token %}
        <label>User Name</label><input type="text" name="username">
        <label>Password</label><input type="password" name="password">
        <input type="submit" value="submit">
    </form>
{% endblock %}

myapp/templates/myapp/mycourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if request.user.is_authenticated %}
        {% if course_list %}
            <ul>
             {% for course in course_list %}
                <li>
                    {{ course.title }}
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>You don't choose any courses!</p>
        {% endif %}
    {% else %}
        <p>You are not a student. Please log in!</p>
    {% endif %}
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="" method="post">
    {% csrf_token %}
    {{ register_form.as_p }}
    <input type="submit" value="submit">
    </form>

{% endblock %}

myapp/templates/myapp/topic.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    {% if  request.user.is_authenticated %}
        Hello {{ request.user }}
    {% else %}
        Hello User
    {% endif %}
{% endblock %}

{% block body_block %}
    <a href="{% url 'myapp:addtopic' %}">Add A New Topic</a>
    {% if topiclist %}
        <h2>Topic List:</h2>
        <ol>
            {% for topic in topiclist %}
                <li><a href="{% url 'myapp:topicdetail' topic.id %}">{{ topic.subject }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/topic_part1.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    {% if  request.user.is_authenticated %}
        Hello {{ request.user }}
    {% else %}
        Hello User
    {% endif %}
{% endblock %}

{% block body_block %}
    <form>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

myapp/templates/myapp/topicdetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <p>Subject: <strong>{{ topicdetail.subject }}</strong></p>
    <p>The number of people interested in the topic:<strong>{{ topicdetail.num_responses}}</strong></p>
    <p>Whether it is an introductory course: <strong>{{ topicdetail.intro_course}}</strong></p>
    <p>Avg_age of people interested in the particular topic: <strong>{{ topicdetail.avg_age}}</strong></p>
    <br><br><br>

    <form action="" method="post">
        {% csrf_token %}
        {{ interest_from.as_p }}
        <input type="submit" value="Submit">
        <input type="reset" value="Reset">
    </form>

{% endblock %}